# Generated by Django 3.0.7 on 2020-06-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191223_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fighter',
            field=models.CharField(blank=True, choices=[(None, 'Select...'), ('amateur', 'Amateur'), ('professional', 'Professional')], max_length=200),
        ),
    ]
