# Generated by Django 2.2.5 on 2019-11-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GymImages',
            new_name='GymImage',
        ),
        migrations.RenameModel(
            old_name='ReviewImages',
            new_name='ReviewImage',
        ),
    ]
