# Generated by Django 2.2.5 on 2019-11-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtdb', '0002_auto_20191109_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gym',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['country', 'city']},
        ),
        migrations.AddField(
            model_name='review',
            name='rating_cost',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
