# Generated by Django 2.2.5 on 2019-12-01 17:23

from django.db import migrations, models
import django.db.models.deletion
import mtdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('mtdb', '0003_auto_20191125_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymimage',
            name='image',
            field=models.ImageField(upload_to=mtdb.models.gym_img_path),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_cost',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_facility',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_location',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_overall',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating_training',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=None),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to=mtdb.models.review_img_path),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mtdb.Review'),
        ),
    ]
