# Generated by Django 2.2.5 on 2019-12-23 21:32

from django.db import migrations, models
import mtdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('mtdb', '0004_auto_20191201_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stay_length',
        ),
        migrations.AddField(
            model_name='review',
            name='training_length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mtdb.models.review_img_path),
        ),
    ]
