# Generated by Django 3.0.5 on 2020-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtdb', '0008_auto_20200525_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='session_type',
            field=models.CharField(choices=[('group', 'Group'), ('private', 'Private')], default='group', max_length=200),
        ),
    ]
